"""Constrain category keys and transaction currencies

Revision ID: 02864ab44319
Revises: 8063e151b1eb
Create Date: 2026-10-06 17:34:32.702618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02864ab44319'
down_revision = '8063e151b1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_user_key', ['user_id', 'key'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_transaction_currency', 'currencies', ['currency_code'], ['code']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_currency', type_='foreignkey')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_user_key', type_='unique')

    # ### end Alembic commands ###
