"""Snapshot transaction base currency

Revision ID: fa22eee54f65
Revises: 02864ab44319
Create Date: 2026-10-06 17:38:32.085557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa22eee54f65'
down_revision = '02864ab44319'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.add_column(
            sa.Column("base_currency_code", sa.String(length=10), nullable=True)
        )
    op.execute(
        sa.text(
            "UPDATE transactions SET base_currency_code = COALESCE("
            "(SELECT base_currency FROM users WHERE users.id = transactions.user_id), "
            "currency_code)"
        )
    )
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column("base_currency_code", nullable=False)
        batch_op.create_foreign_key(
            "fk_transaction_base_currency",
            "currencies",
            ["base_currency_code"],
            ["code"],
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_base_currency', type_='foreignkey')
        batch_op.drop_column('base_currency_code')

    # ### end Alembic commands ###
